### ISSUE TITLE
Breaking changes from the nvim-tree plugin

### ISSUE THREAD

**Issue by simonlearnscoding** [kiyoon/treemux#1]
hey I think a recent commit from the nvim-tree guys broke your plugins, 

https://github.com/nvim-tree/nvim-tree.lua/commit/5aa318c15934efa03d2ac86b493e89792e06c7b6

you might want to pin to an older commit. thank you for your work by the way your tmux plugin is really cool

**Comment by kiyoon** [comment]
It should have been fixed a year ago and I forgot to close it. Thank you!
