### ISSUE TITLE
How to change colors or theme

### ISSUE THREAD

**Issue by stepanzak** [kiyoon/treemux#2]
Hi, thanks for this great plugin.
I can't figure out how to change theme of treemux. I'm open to manually changing color codes, but I have no idea how to do that.
I'm using NvChad with Neovim, if that helps.
Thanks for any help.

**Comment by kiyoon** [comment]
Hi, the only way so far is to copy the `configs/treemux_init.lua` to your dotfiles directory, and change the tmux settings.

```tmux
set -g @treemux-tree-nvim-init-file '~/.your_dotfiles/treemux/treemux_init.lua'
```
