### ISSUE TITLE
Lack of `lsof` cause cwd detecting not work

### ISSUE THREAD

**Issue by fifv** [kiyoon/treemux#3]
This plugin is amazing! 

But the cwd detecting doesn't work after I install `treemux` on Arch Linux. After debugging I found the `lsof` command is not found, which is used here: https://github.com/kiyoon/treemux/blob/b5fa3ebf7c50a812db0892246e78abc571fbf8d7/scripts/nvimtree/watch_and_update.sh#L113

After installing `lsof` everything works smoothly.

I'm new to Linux world, maybe modern distro prefer `fuser` over `lsof` as `lsof` is not installed by default (by the base meta package)?

I think the requirement of `lsof` can be added to README or print some error message when encounter the "command not found" problem :)

**Comment by kiyoon** [comment]
Hi, I'll add this to README. Thank you!
