### ISSUE TITLE
Allow for different editors.

### ISSUE THREAD

**Issue by zhellsh** [kiyoon/treemux#4]
I have an issue with this plug-in. Sure, it is great. But... I want it to respect the value set in $EDITOR. I have no hate against nvim, but all of my plugins are stuck with vim and I do not want to change to nvim. Love the plugin!

**Comment by kiyoon** [comment]
I'm really sorry but this is out of scope.

It is not as simple as just changing the command from nvim to vim. Currently I'm using pynvim to interact with remove neovim instances which won't work smoothly with vim. Also if the `$EDITOR` is something else like helix it gets way more complicated..

**Comment by zhellsh** [comment]
That's fine! I love the project though!

**Comment by kiyoon** [comment]
Thank you so much!!!
