### ISSUE TITLE
The previous key bindings remain after I change the key binding

### ISSUE THREAD

**Issue by roychshao** [kiyoon/treemux#6]
Hi, I can successfully set the key binding to prefix + s by
```
set -g @treemux-tree 's'
```
and when I changed my mind and want the key binding to be prefix + t, I modify it to be
```
set -g @treemux-tree 't'
```
but I notice that both prefix + s and prefix + t (also the default prefix + tab) can toggle the tree.

I have already reload the tmux configuration and reinstall treemux, but the key I set before deletion still works.

**Comment by kiyoon** [comment]
That seems strange. Maybe your tmux configuration automatically recovers from the previous state

**Comment by roychshao** [comment]
Sorry, I just solve it,
I discovered that what I reload is .tmux.conf, but where I do this is .tmux.conf.local, after I source it, the problem vanished.
Sorry for bother you!
By the way, this is a awesome plugin to be an alternative of tmux-sidebar for nvim players~
