### ISSUE TITLE
Incomplete file display issue

### ISSUE THREAD

**Issue by shuai532209720** [kiyoon/treemux#8]
I am using lazyvim, but treemux unable to display hidden files. Press H key,  treemux unable to display all files in the directory

**Comment by kiyoon** [comment]
Refer to the nvim-tree usage. I think if you type `g?` it shows all shortcuts. I think maybe it was `I` to show some types of hidden files like gitignore.

**Comment by shuai532209720** [comment]
Enter `I` will show all files，Thanks!
