### ISSUE TITLE
Treemux editor tries to load my personal config

### ISSUE THREAD

**Issue by Matteo-Exsensia** [kiyoon/treemux#9]
I have my normal neovim config in `~/.config/nvim` and my tmux config in `~/.config/tmux`.

I modified the command from the install procedure to use the correct path `set -g @treemux-tree-nvim-init-file '~/.config/tmux/plugins/treemux/configs/treemux_init.lua'`
but whenever I press `prefix + tab` to open the sidebar I just get a bunch of errors about nvim not founding modules.

In my normal configs I use Packer instead of Lazy, also it appears to me that the errors are all about the file in `~/.config/nvim/after`

I'm new to nvim so I might be missing something, but I'm sure to have everything required in the readme of this repo installed.

If you need the logs let me know

**Comment by kiyoon** [comment]
Hi,

Even if you set the init file, it will still access the after/ dir.

In order to avoid this, you can set nvim command as `NVIM_APPNAME=nvim-treemux nvim`

**Comment by Matteo-Exsensia** [comment]
Hi, thanks for quick response!

I've tried to set the nvim command as you said in my tmux config: 
```
set -g @treemux-nvim-command "NVIM_APPNAME=nvim-treemux nvim"
```
But once I press `prefix + tab` I only get this line:
```
'/home/matteo/.config/tmux/plugins/treemux/scripts/toggle.sh 'NVIM_APPNAME=nvim-treemux nvim,~/.config/tmux/plugins/treemux/configs/treemux_init.lua,,python3,left,40,top,70%,editor,0.5,2,@treemux-refresh-interval-inactive-window,0' '%0'' returned 1
```
So I've tried to solve the problem in a couple of ways:
- Added an alias to command with the env var. Doesn't work, same result
- Moved the command with env var in a script, the sidebar shows up just fine, but the open feature is not working (this part I'm not sure it's related to this issue, I might have done something wrong with `nvim-tree-remote`)

I'm not sure that my solution is what you meant but seams to be working, so thanks!

**Comment by kiyoon** [comment]
Can you make sure you're using the latest treemux and nvim-tree-remote?

**Comment by kiyoon** [comment]
`set -g @treemux-enable-debug-pane 1` this option may help you identify the issues

**Comment by kiyoon** [comment]
You can also just run `/home/matteo/.config/tmux/plugins/treemux/scripts/toggle.sh 'NVIM_APPNAME=nvim-treemux nvim,~/.config/tmux/plugins/treemux/configs/treemux_init.lua,,python3,left,40,top,70%,editor,0.5,2,@treemux-refresh-interval-inactive-window,0' '%0'` manually to see where the error is.

**Comment by Matteo-Exsensia** [comment]
Ok so I updated everything, reinstalled `nvim-tree` and `nvim-tree-remote`, rewrote the configs for them and `nvim-tree` is working fine inside nvim, now I can open the treemux sidebar without any problem or warnings.

Now `NVIM_APPNAME` it's working!

I still can't open files from the treemux sidebar (If I run nvim-tree command  from nvim it works, maybe the issue here is with `nvim-tree-remote`).
But I think this should be another issue or be open in the nvim-tree-remote repo, in the case you want to continue here this is the error that is giving me:
```
E5108: Error executing lua: ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:99: attempt to call field 'system' (a nil value)
stack traceback:
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:99: in function 'remote_nvim_open'
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:216: in function 'open_file_remote_and_folder_local'
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:248: in function <...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:247>
```

**Comment by kiyoon** [comment]
What is the version of your nvim? Maybe I used a newer nvim API.

**Comment by kiyoon** [comment]
I updated `nvim-tree-remote.nvim` to be compatible with nvim < 0.10. Can you update the plugin and try again?

Scusa per il disturbo e grazie per la pazienza

**Comment by metiu19** [comment]
> What is the version of your nvim?
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```
Unfortunately I'm on Ubuntu and using neovim from apt so I'm limited by whatever version Canonical choose, I will eventually set up the ppa or built it from source once I found the time for it.

Anyway I updated the plugin and if I have a neovim instance open in the current tmux window it works flawlessly, otherwise it gives me this error:
```
E5108: Error executing lua: ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:153: attempt to call field 'system' (a nil value)
stack traceback:
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:153: in function 'remote_nvim_open'
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:217: in function 'open_file_remote_and_folder_local'
        ...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:249: in function <...lazy/nvim-tree-remote.nvim/lua/nvim_tree_remote/init.lua:248>
```

> Scusa per il disturbo e grazie per la pazienza

No problem at all, thank you for your support!

**Comment by kiyoon** [comment]
Oops, my bad. I didn't remove all `vim.system` calls. Now it should be fine once you update?

Also, you can download the appimage of neovim manually and put it in `$PATH` to use the latest version.

**Comment by metiu19** [comment]
Yes, now it's fine, thank you very much!

Also thanks for the link to the binary, I didn't know about that

**Comment by kiyoon** [comment]
OK thanks! Feel free to let me know if you need anything :)
